# Form implementation generated from reading ui file 'src/packer_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 427)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_pack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_pack.setObjectName("pushButton_pack")
        self.gridLayout.addWidget(self.pushButton_pack, 1, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_exe = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_exe.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radioButton_exe.setChecked(True)
        self.radioButton_exe.setObjectName("radioButton_exe")
        self.horizontalLayout.addWidget(self.radioButton_exe)
        self.radioButton_ui = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_ui.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radioButton_ui.setObjectName("radioButton_ui")
        self.horizontalLayout.addWidget(self.radioButton_ui)
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton_select = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_select.setObjectName("pushButton_select")
        self.gridLayout.addWidget(self.pushButton_select, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.plainTextEdit_command = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit_command.setMinimumSize(QtCore.QSize(550, 91))
        self.plainTextEdit_command.setReadOnly(True)
        self.plainTextEdit_command.setObjectName("plainTextEdit_command")
        self.verticalLayout.addWidget(self.plainTextEdit_command)
        self.plainTextEdit_console = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit_console.setMinimumSize(QtCore.QSize(550, 250))
        self.plainTextEdit_console.setObjectName("plainTextEdit_console")
        self.verticalLayout.addWidget(self.plainTextEdit_console)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "代码打包"))
        self.pushButton_pack.setText(_translate("MainWindow", "打包"))
        self.radioButton_exe.setText(_translate("MainWindow", "打包.exe"))
        self.radioButton_ui.setText(_translate("MainWindow", "打包.ui"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "文件夹路径"))
        self.pushButton_select.setText(_translate("MainWindow", "选择文件夹"))
