# Form implementation generated from reading ui file 'src/triapprox_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(667, 439)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_reference = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_reference.setObjectName("groupBox_reference")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_reference)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_reference = QtWidgets.QLabel(parent=self.groupBox_reference)
        self.label_reference.setMinimumSize(QtCore.QSize(128, 128))
        self.label_reference.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_reference.setObjectName("label_reference")
        self.gridLayout_2.addWidget(self.label_reference, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_reference)
        self.groupBox_approx = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_approx.setObjectName("groupBox_approx")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_approx)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_approx = QtWidgets.QLabel(parent=self.groupBox_approx)
        self.label_approx.setMinimumSize(QtCore.QSize(128, 128))
        self.label_approx.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_approx.setObjectName("label_approx")
        self.gridLayout_3.addWidget(self.label_approx, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_approx)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_radio = QtWidgets.QHBoxLayout()
        self.horizontalLayout_radio.setObjectName("horizontalLayout_radio")
        self.radioButton_monalisa = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_monalisa.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radioButton_monalisa.setObjectName("radioButton_monalisa")
        self.horizontalLayout_radio.addWidget(self.radioButton_monalisa)
        self.radioButton_firefox = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_firefox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radioButton_firefox.setObjectName("radioButton_firefox")
        self.horizontalLayout_radio.addWidget(self.radioButton_firefox)
        self.radioButton_darwin = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_darwin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radioButton_darwin.setObjectName("radioButton_darwin")
        self.horizontalLayout_radio.addWidget(self.radioButton_darwin)
        self.radioButton_custom = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_custom.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radioButton_custom.setObjectName("radioButton_custom")
        self.horizontalLayout_radio.addWidget(self.radioButton_custom)
        self.pushButton_fit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_fit.setObjectName("pushButton_fit")
        self.horizontalLayout_radio.addWidget(self.pushButton_fit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_radio)
        self.plainTextEdit_log = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit_log.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.plainTextEdit_log.setReadOnly(True)
        self.plainTextEdit_log.setObjectName("plainTextEdit_log")
        self.verticalLayout_2.addWidget(self.plainTextEdit_log)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_plot = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_plot.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox_plot.setObjectName("groupBox_plot")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_plot)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(parent=self.groupBox_plot)
        self.widget.setObjectName("widget")
        self.gridLayout_4.addWidget(self.widget, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_plot)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "几何拟合"))
        self.groupBox_reference.setTitle(_translate("MainWindow", "原图"))
        self.groupBox_approx.setTitle(_translate("MainWindow", "拟合"))
        self.radioButton_monalisa.setText(_translate("MainWindow", "蒙娜丽莎"))
        self.radioButton_firefox.setText(_translate("MainWindow", "火狐"))
        self.radioButton_darwin.setText(_translate("MainWindow", "达尔文"))
        self.radioButton_custom.setText(_translate("MainWindow", "自选"))
        self.pushButton_fit.setText(_translate("MainWindow", "拟合"))
        self.plainTextEdit_log.setPlainText(_translate("MainWindow", "iteration:\n"
"\n"
"metric:\n"
"\n"
"pertubation:"))
        self.groupBox_plot.setTitle(_translate("MainWindow", "拟合曲线"))
